### ISSUE TITLE
Active Log Not Available When Hub is Running

### ISSUE THREAD

**Issue by askovi** [hoobs-org/cli#7]
Opened HelM from the top right menu and typed:

`sudo hbs log`
entered the sudo password then nothing was displayed.
![image](https://user-images.githubusercontent.com/3981552/112928281-518bed00-90e4-11eb-91f6-a626ff03358b.png)

I have 2 bridges running and there are logs available on the logs page. 
I tried also sudo hbs log -d but same result.

**Comment by mkellsy** [comment]
The log file is save on hoobsd exit.
Need to come up with a way to read logs from a live service.
Maybe I could use the IPC.

**Comment by mkellsy** [comment]
I created an IPC route for the active log from the hub.

Fixed in
CLI 4.0.18
HOOBSD 4.0.39
